/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // DefraDB sidebar - autogenerated from the defradb directory
  defraSidebar: [{
    type: "autogenerated",
    dirName: ".",
  }],

  // SourceHub sidebar - autogenerated from the sourcehub directory + API link
  sourcehubSidebar: [
    {
      type: "autogenerated",
      dirName: "."
    },
    {
      type: 'link',
      label: 'API', // The link label
      href: '/sourcehub/api', // The internal path
    },
  ],

  // Orbis sidebar - autogenerated from the orbis directory
  orbisSidebar: [{
    type: "autogenerated",
    dirName: "."
  }],

  // LensVM sidebar - autogenerated from the lensvm directory
  lensvmSidebar: [{
    type: "autogenerated",
    dirName: "."
  }]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
