// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  defraSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
      customProps: {
        rootLabel: "DefraDB",
      },
    },
  ],
};

module.exports = sidebars;
